--DROP TABLE users IF EXISTS;

CREATE TABLE course (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name_course VARCHAR(50),
  id_course  VARCHAR(10),
  tiet VARCHAR(20),
  si_so INTEGER ,
  giao_vien VARCHAR(20),
  phong_hoc VARCHAR(20),
  so_tin_chi INTEGER,
  ghi_chu VARCHAR(500)
);